"""Runtime settings and the budgets that bound every run.

Budgets are not advisory. Each one is enforced at the point where the
corresponding resource is consumed, and exceeding one degrades the run
(a task stops early, a result is truncated) rather than failing it.
"""

from __future__ import annotations

from functools import lru_cache
from pathlib import Path
from typing import Literal

from pydantic import BaseModel, Field
from pydantic_settings import BaseSettings, SettingsConfigDict

ProviderMode = Literal["fake", "local", "cloud"]

# Repository root, derived from this file's location rather than the process
# working directory, so the demo warehouse resolves the same way under
# pytest, uvicorn and the container entrypoint.
PACKAGE_ROOT = Path(__file__).resolve().parent
REPO_ROOT = PACKAGE_ROOT.parent.parent


class Budgets(BaseModel):
    """Hard ceilings on a single analysis run."""

    max_analysis_tasks: int = Field(default=6, ge=1, le=24)
    max_tool_calls_per_task: int = Field(default=6, ge=1, le=32)
    max_total_tool_calls: int = Field(default=48, ge=1, le=512)
    max_llm_calls: int = Field(default=40, ge=1, le=400)
    max_output_tokens: int = Field(default=2048, ge=128, le=32768)
    max_runtime_seconds: float = Field(default=300.0, gt=0)
    max_followup_rounds: int = Field(default=1, ge=0, le=1)

    # Result shaping. `max_result_rows` is what a tool will return to an
    # agent; `max_sample_rows` is the much smaller ceiling on raw row
    # disclosure, which is the only path by which unaggregated user data
    # reaches a prompt.
    max_result_rows: int = Field(default=500, ge=1, le=1000)
    max_sample_rows: int = Field(default=20, ge=1, le=20)
    max_chart_rows: int = Field(default=200, ge=1, le=1000)
    max_sql_length: int = Field(default=8000, ge=100, le=64000)
    query_timeout_seconds: float = Field(default=20.0, gt=0)

    # Uploads.
    max_upload_bytes: int = Field(default=25 * 1024 * 1024, ge=1024)


class Settings(BaseSettings):
    """Process configuration, all overridable by environment variable."""

    model_config = SettingsConfigDict(
        env_prefix="AAE_",
        env_file=".env",
        env_file_encoding="utf-8",
        extra="ignore",
    )

    # Provider selection. `fake` is the default precisely so that tests, CI,
    # the frontend and recorded replay never need a credential.
    provider_mode: ProviderMode = "fake"
    ollama_base_url: str = "http://127.0.0.1:11434"
    ollama_model: str = "qwen2.5:7b-instruct"
    cloud_model: str = "claude-sonnet-5"
    cloud_api_key: str | None = None
    cloud_base_url: str = "https://api.anthropic.com"

    # When false the API refuses to start new live analyses and serves
    # recordings only. This is the safe public-demo posture.
    live_analytics_enabled: bool = False
    uploads_enabled: bool = True

    # Storage. `var/` is gitignored; the demo warehouse is regenerated by
    # `make data` and the per-session databases are ephemeral.
    data_dir: Path = REPO_ROOT / "var" / "warehouse"
    upload_dir: Path = REPO_ROOT / "var" / "uploads"
    recordings_dir: Path = REPO_ROOT / "examples" / "recordings"

    session_ttl_seconds: float = 3600.0
    max_concurrent_sessions: int = 32
    max_worker_concurrency: int = 4

    # MCP. The agent always talks to analytics through an MCP client; this
    # chooses whether that client is an in-process connection to the server
    # object or a Streamable HTTP connection to a URL.
    mcp_transport: Literal["in-process", "http"] = "in-process"
    mcp_http_url: str = "http://127.0.0.1:8000/mcp"

    log_level: str = "INFO"
    log_json: bool = True

    budgets: Budgets = Field(default_factory=Budgets)

    @property
    def demo_warehouse_dir(self) -> Path:
        return self.data_dir / "commerce"


@lru_cache(maxsize=1)
def get_settings() -> Settings:
    """Process-wide settings, read once."""
    return Settings()


def reset_settings_cache() -> None:
    """Drop the cached settings. Used by tests that patch the environment."""
    get_settings.cache_clear()
